# Generated by Django 4.1 on 2022-09-03 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desafio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_filho',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='desafio.item'),
        ),
    ]
