# Generated by Django 4.1 on 2022-09-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("desafio", "0002_item_item_filho"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="lista",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="usuario",
            name="name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
