# Generated by Django 4.1 on 2022-09-03 05:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("desafio", "0003_item_name_lista_name_usuario_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="item_filho",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="desafio.item",
            ),
        ),
    ]
